# Generated by Django 5.1.1 on 2024-10-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('self', 'self'), ('financial', 'financial'), ('skills', 'skills'), ('skill', 'skill'), ('guide', 'guide'), ('tutorial', 'tutorial'), ('links', 'links')], max_length=50)),
                ('file', models.FileField(upload_to='upload/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
